name: platzi-langchain
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - ruff
  - requests
  - jupyter
  - notebook
  - ipykernel
  - pip:
    - langchain
    - langchain-community
    - langchain-ollama
    - langchain-chroma
    - pypdf
    - -e .